const ordersData = [
  {
    id: "ORD123",
    reason: "Damaged item",
    store_name: "Yamm Store 1",
    store_logo: "https://via.placeholder.com/50",
    store_url: "https://yamm.sa",
    amount: 299.99,
    active: true,
    decision: null,
    items: [
      { name: "Laptop", id: "ITEM1", price: 999.99, quantity: 1 },
      { name: "Mouse", id: "ITEM2", price: 49.99, quantity: 2 },
    ],
  },
  {
    id: "ORD124",
    reason: "Wrong item received",
    store_name: "Yamm Store 2",
    store_logo: "https://via.placeholder.com/50",
    store_url: "https://yamm.sa",
    amount: 149.99,
    active: false,
    decision: null,
    items: [{ name: "Smartphone", id: "ITEM3", price: 699.99, quantity: 1 }],
  },
  {
    id: "ORD125",
    reason: "Size issue",
    store_name: "Yamm Store 3",
    store_logo: "https://via.placeholder.com/50",
    store_url: "https://yamm.sa",
    amount: 79.99,
    active: true,
    decision: "Pending",
    items: [
      { name: "T-shirt", id: "ITEM4", price: 19.99, quantity: 2 },
      { name: "Jeans", id: "ITEM5", price: 39.99, quantity: 1 },
    ],
  },
  {
    id: "ORD126",
    reason: "Late delivery",
    store_name: "Yamm Store 4",
    store_logo: "https://via.placeholder.com/50",
    store_url: "https://yamm.sa",
    amount: 499.99,
    active: false,
    decision: "Approved",
    items: [
      { name: "Headphones", id: "ITEM6", price: 199.99, quantity: 1 },
      { name: "Bluetooth Speaker", id: "ITEM7", price: 99.99, quantity: 3 },
    ],
  },
  {
    id: "ORD127",
    reason: "Defective product",
    store_name: "Yamm Store 5",
    store_logo: "https://via.placeholder.com/50",
    store_url: "https://yamm.sa",
    amount: 399.99,
    active: true,
    decision: null,
    items: [
      { name: "Gaming Keyboard", id: "ITEM8", price: 149.99, quantity: 1 },
      { name: "Gaming Mouse", id: "ITEM9", price: 89.99, quantity: 2 },
    ],
  },
  {
    id: "ORD128",
    reason: "Not as described",
    store_name: "Yamm Store 6",
    store_logo: "https://via.placeholder.com/50",
    store_url: "https://yamm.sa",
    amount: 59.99,
    active: false,
    decision: "Rejected",
    items: [
      { name: "Lamp", id: "ITEM10", price: 29.99, quantity: 1 },
      { name: "Wall Clock", id: "ITEM11", price: 19.99, quantity: 1 },
    ],
  },
  {
    id: "ORD129",
    reason: "Product expired",
    store_name: "Yamm Store 7",
    store_logo: "https://via.placeholder.com/50",
    store_url: "https://yamm.sa",
    amount: 29.99,
    active: true,
    decision: null,
    items: [{ name: "Protein Bar", id: "ITEM12", price: 9.99, quantity: 3 }],
  },
  {
    id: "ORD130",
    reason: "Incomplete package",
    store_name: "Yamm Store 8",
    store_logo: "https://via.placeholder.com/50",
    store_url: "https://yamm.sa",
    amount: 349.99,
    active: false,
    decision: "Approved",
    items: [
      { name: "Smartwatch", id: "ITEM13", price: 249.99, quantity: 1 },
      { name: "Charging Cable", id: "ITEM14", price: 29.99, quantity: 2 },
    ],
  },
  {
    id: "ORD131",
    reason: "Different color received",
    store_name: "Yamm Store 9",
    store_logo: "https://via.placeholder.com/50",
    store_url: "https://yamm.sa",
    amount: 89.99,
    active: true,
    decision: "Pending",
    items: [
      { name: "Wireless Earbuds", id: "ITEM15", price: 89.99, quantity: 1 },
    ],
  },
  {
    id: "ORD132",
    reason: "Wrong size",
    store_name: "Yamm Store 10",
    store_logo: "https://via.placeholder.com/50",
    store_url: "https://yamm.sa",
    amount: 129.99,
    active: false,
    decision: "Rejected",
    items: [
      { name: "Running Shoes", id: "ITEM16", price: 129.99, quantity: 1 },
    ],
  },
];

export default ordersData;
